### ISSUE TITLE
Add a Splash/Welcome Screen

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/Covid-App#2]

**Comment by rohitjakhar** [comment]
I am able to find the problem and I am currently working on it, kindly assign me to this issue.

**Comment by swapnilsparsh** [comment]
> I am able to find the problem and I am currently working on it, kindly assign me to this issue.

Good Luck 👍🏼

**Comment by rohitjakhar** [comment]
Check PR request. I add welcome screen and make clean code

**Comment by swapnilsparsh** [comment]
> Check PR request. I add welcome screen and make clean code

Sure.
Will review it tonight. 🙂

**Comment by swapnilsparsh** [comment]
Issue resolved by @rohitjakhar #3
